# -*- coding: utf-8 -*-
"""Weather Internship Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KtM4tKgxylSlEp1w4B1_RseVuo9DcPj
"""

import pandas as pd
import numpy as np

## 43029_Chandrapur.csv

df = pd.read_csv("/content/43029_Chandrapur.csv")
# Correctly drop the column named 'AW'
df = df.drop(columns=['AW'])

df = df.drop(columns=['EVP', 'DRNRF(hrs)',
       'DRNRF(mnts)', 'SSH', 'TS', 'N', 'FFF', 'D', 'TOCSQ', 'DU', 'RA', 'DZ',
       'SN', 'SL', 'HA', 'TH', 'DS', 'FG', 'GA', 'T', 'G', 'DUR', 'T.1', 'G.1',
       'DUR.1', 'T.2', 'G.2', 'DUR.2', 'T.3', 'G.3', 'DUR.3', 'Unnamed: 39',
       'RF_num'])

display(df.head())
df.shape

# Replace NaN values in 'MAX' and 'MIN' for df
df['MAX'].fillna(32, inplace=True)
df['MIN'].fillna(20, inplace=True)
display(df.head())

## 42935_Washim.csv

df1 = pd.read_csv("/content/42935_Washim.csv")
# Correctly drop the column named 'AW'
df1 = df1.drop(columns=['AW','EVP',
       'DRNRF(hrs)', 'DRNRF(mnts)', 'SSH', 'TS', 'N', 'FFF', 'D', 'TOCSQ',
       'DU', 'RA', 'DZ', 'SN', 'SL', 'HA', 'TH', 'DS', 'FG', 'GA', 'T', 'G',
       'DUR', 'T.1', 'G.1', 'DUR.1', 'T.2', 'G.2', 'DUR.2', 'T.3', 'G.3',
       'DUR.3'])
print(df.columns)

df1.head()

# Replace NaN values in 'MAX' and 'MIN' for df1
df1['MAX'].fillna(32, inplace=True)
df1['MIN'].fillna(20, inplace=True)
display(df1.head())

## 42939_Wardha.csv

df2 = pd.read_csv("/content/42939_Wardha.csv")

# Select only the desired columns directly
df2 = df2[['INDEX', 'YEAR', 'MN', 'DT', 'MAX', 'MIN', 'RF']]

df2['RF'] = pd.to_numeric(df2['RF'], errors='coerce')

display(df2.head())
df2.shape

# Replace NaN values in 'MAX' and 'MIN' for df2
df2['MAX'].fillna(32, inplace=True)
df2['MIN'].fillna(20, inplace=True)
display(df2.head())

df4= pd.read_csv("/content/42933_Akola.csv")

df4 = df4.drop(columns=['AW'])

df4.head()

# Replace NaN values in 'MAX' and 'MIN' for df4
df4['MAX'].fillna(32, inplace=True)
df4['MIN'].fillna(20, inplace=True)
display(df4.head())

"""### Saving the cleaned DataFrames to new CSV files"""

# Save the cleaned df to a new CSV file
df.to_csv('/content/df_cleaned.csv', index=False)
print('df_cleaned.csv saved successfully.')

# Save the cleaned df1 to a new CSV file
df1.to_csv('/content/df1_cleaned.csv', index=False)
print('df1_cleaned.csv saved successfully.')

# Save the cleaned df2 to a new CSV file
df2.to_csv('/content/df2_cleaned.csv', index=False)
print('df2_cleaned.csv saved successfully.')

# Save the cleaned df4 to a new CSV file
df4.to_csv('/content/df4_cleaned.csv', index=False)
print('df4_cleaned.csv saved successfully.')

"""# **Weekly Conversion**"""

akola = pd.read_csv("/content/akola_cleaned.csv")
print(akola)
print(akola.shape)

chandrapur = pd.read_csv("/content/chandrapur_cleaned.csv")
print(chandrapur)

wardha = pd.read_csv("/content/wardha_clean.csv")
# wardha = wardha.drop(columns=['Unnamed: 0'])
wardha.to_csv("/content/wardha_clean.csv", index=False)
print('"Unnamed: 0" column permanently removed from wardha_clean.csv')
print(wardha)
print(wardha.shape)

washim = pd.read_csv("/content/washim_cleaned.csv")
print(washim)

# print(washim.shape)

# from google.colab import files
# files.download("/content/chandrapur_cleaned.csv")

## sum of RF attribute

wardha_interval_avg = wardha.groupby(wardha.index // 7)['RF'].sum()
wardha_interval_avg

wardha['RF2'] = (wardha.index // 7).map(wardha_interval_avg)
display(wardha.head(30))
wardha.shape

chandrapur_w = pd.read_csv("/content/chandrapur_weekly.csv")
chandrapur_w

wardha_w = pd.read_csv("/content/wardha_weekly.csv")
wardha_w

akola_a = pd.read_csv("/content/akola_weekly.csv")
akola_a

washim_w = pd.read_csv("/content/washim_weekly.csv")
washim_w

chandrapur_add = pd.read_csv("/content/chandrapur_cleaned.csv")
# Create a proper 'Date' column from YEAR, MN, and DT
chandrapur_add['Date'] = pd.to_datetime(chandrapur_add[['YEAR', 'MN', 'DT']].astype(str).agg('-'.join, axis=1), format='%Y-%m-%d')
chandrapur_add.head(10)

"""# **Dry Spell Data Preparation**"""

# Calculate the continuous week number within each year
# Days from the start of the year (dt.dayofyear - 1), divided by 7, plus 1 to start weeks from 1
chandrapur_add['week'] = (chandrapur_add['Date'].dt.dayofyear - 1) // 7 + 1

display(chandrapur_add.head(15))

chandrapur_add.to_csv('/content/chandrapur_add_updated.csv', index=False)
print('chandrapur_add_updated.csv saved successfully.')

final_chandrapur = pd.read_csv("/content/chandrapur_with_week (1).csv")
final_chandrapur = final_chandrapur.drop(columns=['MIN','MAX'])
final_chandrapur

final_chandrapur.to_csv("final_chandrapur.csv",index=False)